apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"theia-deployment","namespace":"integration-tests"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"theia"}},"template":{"metadata":{"labels":{"app":"theia"}},"spec":{"containers":[{"env":[{"name":"KAFKA_BROKERS","value":"10.43.186.12:9092"},{"name":"EPS","value":"10"},{"name":"CHANNELS","value":"5"},{"name":"StatSD_Host","value":"none"}],"image":"flowworks-carlsolutions.azurecr.io/flowworks/theia:al20211012","name":"theia-container"}],"dnsPolicy":"ClusterFirst","hostNetwork":true,"imagePullSecrets":[{"name":"regsecret"}]}}}}
  creationTimestamp: "2021-10-14T09:02:18Z"
  generation: 1
  name: theia-deployment
  namespace: integration-tests
  resourceVersion: "33453453"
  uid: 81358770-ebc0-436e-ad0a-f6ac43edce47
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: theia
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: theia
    spec:
      containers:
      - env:
        - name: KAFKA_BROKERS
          value: 10.43.238.93:9092
        - name: EPS
          value: "10"
        - name: CHANNELS
          value: "5"
        - name: StatSD_Host
          value: none
        image: flowworks-carlsolutions.azurecr.io/flowworks/theia:al20211012
        imagePullPolicy: IfNotPresent
        name: theia-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-14T09:02:19Z"
    lastUpdateTime: "2021-10-14T09:02:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-14T09:02:18Z"
    lastUpdateTime: "2021-10-14T09:02:19Z"
    message: ReplicaSet "theia-deployment-85ccfbb689" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
